//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EAVStoreClient
{
    using System;
    using System.Collections.Generic;
    
    public partial class Attribute
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Attribute()
        {
            this.Value = new HashSet<Value>();
        }
    
        public int Attribute_ID { get; set; }
        public int Container_ID { get; set; }
        public int Data_Type_ID { get; set; }
        public string Name { get; set; }
        public string Data_Name { get; set; }
        public string Display_Text { get; set; }
        public bool Is_Key { get; set; }
        public int Sequence { get; set; }
        public Nullable<bool> Variable_Units { get; set; }
    
        public virtual Container Container { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Value> Value { get; set; }
        public virtual Data_Type Data_Type { get; set; }
    }
}
