//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EAVStoreClient
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class MicroEAVContext : DbContext
    {
        public MicroEAVContext()
            : base("name=MicroEAVContext")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Attribute> Attributes { get; set; }
        public virtual DbSet<Container> Containers { get; set; }
        public virtual DbSet<Context> Contexts { get; set; }
        public virtual DbSet<Data_Type> Data_Type { get; set; }
        public virtual DbSet<Entity> Entities { get; set; }
        public virtual DbSet<Instance> Instances { get; set; }
        public virtual DbSet<Subject> Subjects { get; set; }
        public virtual DbSet<Value> Values { get; set; }
        public virtual DbSet<Unit> Units { get; set; }
    }
}
